CREATE TABLE `user` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `createdBy` VARCHAR(32) COLLATE utf8mb4_bin DEFAULT NULL,
  `updatedBy` VARCHAR(32) COLLATE utf8mb4_bin DEFAULT NULL,
  `createTime` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updateTime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT(11) DEFAULT '1',
  `isDeleted` CHAR(1) COLLATE utf8mb4_bin DEFAULT 'N',
  `userName` VARCHAR(64) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin